CREATE DATABASE packages;
USE packages;
CREATE TABLE offer (Id int(11) NOT NULL AUTO_INCREMENT, Text varchar(255) NOT NULL, CreateDate timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (Id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1;
CREATE USER 'app'@'%' IDENTIFIED BY 'senha.123';
GRANT ALL PRIVILEGES ON *.* TO 'app'@'%';
